services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_WS_URL=ws://localhost:4000
    depends_on:
      - backend
    command: [ "bun", "run", "dev" ]

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: [ "bun", "watch" ]

  worker:
    build: ./worker
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    command: [ "redis-server", "/data/redis.conf" ]
