services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - "VITE_WS_URL=ws://localhost:${BACKEND_PORT}"
    depends_on:
      - backend
    command: [ "bun", "run", "dev" ]

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: [ "bun", "watch" ]

  worker:
    build: ./worker
    ports:
      - "${WORKER_PORT}:${WORKER_PORT}"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./redis:/data
    command: [ "redis-server", "/data/redis.conf" ]
