services:
  backend:
    build:
      context: .
      dockerfile: backend/dockerfile.production
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      - redis
    command: [ "bun", "run", "start" ]

  worker:
    build: ./worker
    expose:
      - "${WORKER_PORT}"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    expose:
      - "${REDIS_PORT}"
    volumes:
      - ./redis:/data
    command: [ "redis-server", "/data/redis.conf" ]
