FROM golang:1.23 AS builder

WORKDIR /app
COPY . .

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o worker

FROM alpine:latest

COPY --from=builder /app/worker /worker

RUN chmod +x /worker

CMD [ "/worker" ]
